# Generated by Django 3.1.7 on 2021-08-06 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'verbose_name_plural': 'Patient Information'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='Age',
            field=models.IntegerField(default=1, max_length=200, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
